CREATE TYPE "public"."content_type" AS ENUM('text', 'image', 'video', 'link', 'mixed');--> statement-breakpoint
CREATE TYPE "public"."post_type" AS ENUM('original', 'repost', 'quote');--> statement-breakpoint
CREATE TYPE "public"."source_type" AS ENUM('twitter', 'weibo', 'reddit', 'instagram', 'facebook', 'tiktok', 'youtube', 'rss', 'other');--> statement-breakpoint
CREATE TABLE "posts" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"external_id" varchar(255) NOT NULL,
	"title" varchar(500),
	"content" text,
	"type" "post_type" DEFAULT 'original' NOT NULL,
	"contentType" "content_type" DEFAULT 'text' NOT NULL,
	"sourceType" "source_type" NOT NULL,
	"rss_source" varchar(1000),
	"author_id" varchar(255) NOT NULL,
	"author_name" varchar(255),
	"author_username" varchar(255),
	"author_avatar" varchar(1000),
	"author_verified" boolean DEFAULT false,
	"original_post_id" varchar(255),
	"original_author_id" varchar(255),
	"original_author_name" varchar(255),
	"media_urls" text,
	"link_url" varchar(1000),
	"link_title" varchar(500),
	"link_description" text,
	"link_image" varchar(1000),
	"hashtags" text,
	"mentions" text,
	"view_count" bigint DEFAULT 0,
	"like_count" bigint DEFAULT 0,
	"comment_count" bigint DEFAULT 0,
	"share_count" bigint DEFAULT 0,
	"repost_count" bigint DEFAULT 0,
	"location" varchar(255),
	"latitude" varchar(50),
	"longitude" varchar(50),
	"language" varchar(10) DEFAULT 'en',
	"is_pinned" boolean DEFAULT false,
	"is_deleted" boolean DEFAULT false,
	"is_private" boolean DEFAULT false,
	"published_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_sync_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"external_id" varchar(255) NOT NULL,
	"post_id" integer NOT NULL,
	"content" text,
	"author_id" varchar(255) NOT NULL,
	"author_name" varchar(255),
	"author_username" varchar(255),
	"author_avatar" varchar(1000),
	"author_verified" boolean DEFAULT false,
	"media_urls" text,
	"mentions" text,
	"like_count" bigint DEFAULT 0,
	"is_pinned" boolean DEFAULT false,
	"is_deleted" boolean DEFAULT false,
	"is_hidden" boolean DEFAULT false,
	"language" varchar(10) DEFAULT 'en',
	"published_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_sync_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;